name: Get aptos
description: Download `aptos` tool for Aptos network.
author: Pontem Network team
branding:
  icon: sunrise
  color: purple
inputs:
  version:
    default: "latest"
    description: Aptos version (ex. `aptos-cli-v0.1.1` or default `latest`).
    required: false
  token:
    description: GITHUB_TOKEN. Optional
    required: false
  prerelease:
    default: "false"
    description: Allow pre-release. False by default.
    required: false
runs:
  using: "composite"
  steps:

    - name: Download
      run: $GITHUB_ACTION_PATH/aptos_download.sh
      shell: bash
      env:
        APTOS_VERSION: ${{inputs.version}}
        APTOS_PRERELEASE: ${{inputs.prerelease}}
        SECRET_TOKEN: ${{inputs.token}}